<?php

    if (!defined('BASEPATH'))
        exit('No direct script access allowed');

    $config['default_css'] = array(
        'bootstrap' => array('name' => 'assets/css/bootstrap.min.css'),
        'entypo' => array('name' => 'assets/css/entypo.css'),
        'owlcarousel' => array('name' => 'assets/css/owl.carousel.css'),
        'owltheme' => array('name' => 'assets/css/owl.theme.css'),
        'magnific' => array('name' => 'assets/css/magnific-popup.css'),
        'flexslider' => array('name' => 'assets/css/flexslider.css'),
        'frontend' => array('name' => 'assets/css/frontend.css'),
        'theme' => array('name' => 'assets/css/theme.css'),
        'style' => array('name' => 'assets/css/style.css'),
        'theme-elements' => array('name' => 'assets/css/theme-elements.css'),
        'animate' => array('name' => 'assets/css/animate.min.css'),
        'selectize' => array('name' => 'assets/js/plugins/selectize.js-master/dist/css/selectize.css'),
        'main' => array('name' => 'assets/css/main.css'),
    );

    $config['default_js'] = array(
        'jquery' => array('name' => 'assets/js/jquery-1.11.0.min.js'),
        'jquery-migrate' => array('name' => 'assets/js/jquery-migrate-1.2.1.min.js'),
        'bootstrap' => array('name' => 'assets/js/bootstrap.js'),
        'flexnav' => array('name' => 'assets/js/jquery.flexnav.min.js'),
        'hoverIntent' => array('name' => 'assets/js/jquery.hoverIntent.minified.js'),
        'flickrfeed' => array('name' => 'assets/js/jquery.flickrfeed.js'),
        'magnific' => array('name' => 'assets/js/jquery.magnific-popup.js'),
        'owlcarousel' => array('name' => 'assets/js/owl.carousel.min.js'),
        'jquery-fitvids' => array('name' => 'assets/js/jquery.fitvids.js'),
        'appear' => array('name' => 'assets/js/jquery.appear.js'),
        'stellar' => array('name' => 'assets/js/jquery.stellar.min.js'),
        'flexslider' => array('name' => 'assets/js/jquery.flexslider-min.js'),
        'countTo' => array('name' => 'assets/js/jquery.countTo.js'),
        'validate' => array('name' => 'assets/js/jquery.validate.js'),
        'newsletter' => array('name' => 'assets/js/newsletter.js'),
        'custom' => array('name' => 'assets/js/custom.js'),
        'modernizr' => array('name' => 'assets/js/modernizr.js'),
        'rating' => array('name' => 'assets/js/star-rating.js'),
        'bootbox' => array('name' => 'assets/js/bootbox.js'),
        //'selectize' => array('name' => 'assets/js/plugins/selectize.js-master/dist/js/standalone/selectize.js'),
        'bxslider' => array('name' => 'assets/js/jquery.bxslider.min.js'),
        'blockUI' => array('name' => 'assets/js/blockUI.js'),
      'angu' => array('name' => 'assets/js/angu.js'),
    );


    $config['admin_default_css'] = array(
        'bootstrap' => array('name' => 'assets/bootstrap/css/bootstrap.min.css'),
        'select2' => array('name' => 'assets/plugins/select2/select2.css'),
        'AdminLTE' => array('name' => 'assets/css/AdminLTE.css'),
        'allskins' => array('name' => 'assets/css/skins/_all-skins.min.css'),
        'icheck' => array('name' => 'assets/plugins/iCheck/square/_all.css'),
        'icheck-blue' => array('name' => 'assets/plugins/iCheck/flat/blue.css'),
        'jquery-ui.min' => array('name' => 'assets/css/jquery-ui.min.css'),
    );

    $config['admin_default_js'] = array(
        'jquery' => array('name' => 'assets/plugins/jQuery/jQuery-2.1.4.min.js'),
        'bootstrap' => array('name' => 'assets/bootstrap/js/bootstrap.min.js'),
        'fastclick' => array('name' => 'assets/plugins/fastclick/fastclick.min.js'),
        'app' => array('name' => 'assets/js/app.min.js'),
        'demo' => array('name' => 'assets/js/demo.js'),
        'general' => array('name' => 'assets/js/general.js'),
        'blockUI' => array('name' => 'assets/js/blockUI.js'),
        'icheck' => array('name' => 'assets/plugins/iCheck/icheck.min.js'),
        'select2' => array('name' => 'assets/plugins/select2/select2.js'),
        'main' => array('name' => 'assets/css/main.css'),
        'jquery-ui.min' => array('name' => 'assets/js/jquery-ui.min.js'),
    );

    $config['client_default_css'] = array(
        'bootstrap' => array('name' => 'assets/bootstrap/css/bootstrap.min.css'),
        'AdminLTE' => array('name' => 'assets/css/AdminLTE.css'),
        'allskins' => array('name' => 'assets/css/skins/_all-skins.min.css'),
        'icheck-blue' => array('name' => 'assets/plugins/iCheck/flat/blue.css'),
    );

    $config['client_default_js'] = array(
        'jquery' => array('name' => 'assets/plugins/jQuery/jQuery-2.1.4.min.js'),
        'bootstrap' => array('name' => 'assets/bootstrap/js/bootstrap.min.js'),
        'fastclick' => array('name' => 'assets/plugins/fastclick/fastclick.min.js'),
        'app' => array('name' => 'assets/js/app.min.js'),
        'demo' => array('name' => 'assets/js/demo.js'),
        'general' => array('name' => 'assets/js/general.js'),
        'blockUI' => array('name' => 'assets/js/blockUI.js'),
        'icheck' => array('name' => 'assets/plugins/iCheck/icheck.min.js'),
    );


    $config['public_default_css'] = array(
        'bootstrap.min' => array('name' => 'assets/public/css/bootstrap.min.css'),
        'main' => array('name' => 'assets/public/css/main.css', 'id' => 'color-switcher-link'),
    );

    $config['public_default_js'] = array(
        'jquery' => array('name' => 'assets/public/js/jquery-1.11.3.min.js'),
        'bootstrap' => array('name' => 'assets/bootstrap/js/bootstrap.min.js'),    
        'angu' => array('name' => 'assets/js/angu.js'),
    );

    $config['css_arr'] = array(
        'datepicker' => array('name' => 'assets/plugins/datepicker/bootstrap-datepicker.min.css'),
        'jquery.dataTables.bootstrap' => array('name' => 'assets/plugins/datatables/dataTables.bootstrap.css'),
        'datatables' => array('name' => 'assets/plugins/datatable/css/bootstrap.datatable.min.css'),
        'colorbox' => array('name' => 'assets/plugins/colorbox/colorbox.css'),
        'datepicker' => array('name' => 'assets/plugins/datepicker/bootstrap-datepicker.min.css'),
        'timepicker' => array('name' => 'assets/plugins/datepicker/bootstrap-timepicker.css'),
        'datatables-buttons' => array('name' => 'assets/plugins/datatable/css/buttons.dataTables.min.css'),
        'icheck' => array('name' => 'assets/plugins/iCheck/skins/square/_all.css'),
        'dashboard' => array('name' => 'assets/css/dashboard.css'),
        'selectize' => array('name' => 'assets/js/selectize/dist/css/selectize.bootstrap3.css'),
        'dropify' => array('name' => 'assets/plugins/dropify/css/dropify.css'),
        'fullcalendar' => array('name' => 'assets/plugins/calendar/fullcalendar.css'),
        'fullcalendar-print' => array('name' => 'assets/plugins/calendar/fullcalendar.print.css', 'media' => 'print'),
        'colorpicker' => array('name' => 'assets/plugins/colorpicker/bootstrap-colorpicker.min.css'),
        'bootstrap-switch' => array('name' => 'assets/css/bootstrap/css/bootstrap-switch.css'),
        'jquery.datetimepicker' => array('name' => 'assets/plugins/datetimepicker-master/jquery.datetimepicker.css'),
        'toastr' => array('name' => 'assets/plugins/toastr/toastr.css'),
        'qtip.min' => array('name' => 'assets/plugins/qtip/qtip.min.css'),
        'jquery-scrollbar' => array('name' => 'assets/plugins/jquery-scrollbar/jquery.mCustomScrollbar.css'),
        'easy-autocomplete' => array('name' => 'assets/plugins/EasyAutocomplete-1.3.5/easy-autocomplete.css'),
        'easy-autocomplete.themes' => array('name' => 'assets/plugins/EasyAutocomplete-1.3.5/easy-autocomplete.css'),
        'jquery.steps' => array('name' => 'assets/plugins/jquery-steps-master/jquery.steps.css'),
        'fileinput' => array('name' => 'assets/plugins/fileinput/fileinput.css'),
        'colorbox' => array('name' => 'assets/plugins/colorbox/colorbox.css'),
        'bootstrap-tagsinput' => array('name' => 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css'),
        'bootstrap-wysihtml5' => array('name' => 'assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.css'),
        'jquery-ui' => array('name' => 'assets/public/css/jquery-ui.css'),
        'melon.datepicker' => array('name' => 'assets/public/css/melon.datepicker.css'),
        'multiple-select' => array('name' => 'assets/plugins/multiple-select-master/multiple-select.css'),
        'jquery-tree' => array('name' => 'assets/plugins/jquery-tree-master/src/css/jquery.tree.css'),
        'select2' => array('name' => 'assets/plugins/select2/select2.css'),
        'jquery-ui-1.12.1.custom' => array('name' => 'assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.css'),
        'bootstrap-tagsinput' => array('name' => 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.css'),
        'bootstrap-select-1.11.2' => array('name' => 'assets/plugins/bootstrap-select-1.11.2/dist/css/bootstrap-select.css'),
        'jquery.tipsy' => array('name' => 'assets/plugins/tipsy-master/src/stylesheets/tipsy.css'),
        'main' => array('name' => 'assets/css/main.css'),
        'owl.carousel' => array('name' => 'assets/public/css/owl.carousel.css'),
        'jquery.fancybox' => array('name' => 'assets/public/js/fancybox/jquery.fancybox.css'),
    );

    $config['js_arr'] = array(
        'jquery.dataTables' => array('name' => 'assets/plugins/datatables/jquery.dataTables.min.js'),
        'jquery.dataTables.bootstrap' => array('name' => 'assets/plugins/datatables/dataTables.bootstrap.min.js'),
        'datepicker' => array('name' => 'assets/plugins/datepicker/bootstrap-datepicker.min.js'),
        'timepicker' => array('name' => 'assets/plugins/datepicker/bootstrap-timepicker.js'),
        'dataTables.fnFilterOnReturn' => array('name' => 'assets/plugins/datatables/dataTables.fnFilterOnReturn.js'),
        'dataTables.fnReloadAjax' => array('name' => 'assets/plugins/datatables/fnReloadAjax.js'),
        'jquery.validate.min' => array('name' => 'assets/js/validation/jquery.validate.min.js'),
        'additional-methods.min' => array('name' => 'assets/plugins/validation/additional-methods.min.js'),
        'bootstrap.datatables' => array('name' => 'assets/plugins/datatable/js/dataTables.bootstrap.js'),
        'ckeditor' => array('name' => 'assets/plugins/ckeditor/ckeditor.js'),
        'jquery-ui' => array('name' => 'assets/js/jquery-ui.min.js'),
        'colorbox' => array('name' => 'assets/plugins/colorbox/jquery.colorbox.js'),
        'inputmasked' => array('name' => 'assets/js/jquery.maskedinput.js'),
        'button-print' => array('name' => 'assets/plugins/datatable/js/buttons.print.min.js'),
        'datatable-button' => array('name' => 'assets/plugins/datatable/js/dataTables.buttons.min.js'),
        'jquery.validate' => array('name' => 'assets/plugins/validation/jquery.validate.min.js'),
        'icheck' => array('name' => 'assets/plugins/iCheck/js/icheck.min.js'),
        'chart' => array('name' => 'assets/js/chart.min.js'),
        'easypiechart' => array('name' => 'assets/js/easypiechart.js'),
        'chart-data' => array('name' => 'assets/js/chart-data.js'),
        'easypiechart-data' => array('name' => 'assets/js/easypiechart-data.js'),
        'lumino' => array('name' => 'assets/js/lumino.glyphs.js'),
        'googlemap' => array('name' => 'assets/js/googlemap.js'),
        'location_picker' => array('name' => 'assets/js/locationpicker.jquery.js'),
        'selectize' => array('name' => 'assets/js/selectize/dist/js/standalone/selectize.js'),
        'colorpicker' => array('name' => 'assets/plugins/colorpicker/bootstrap-colorpicker.min.js'),
        'dropify' => array('name' => 'assets/plugins/dropify/js/dropify.js'),
        'moment' => array('name' => 'assets/plugins/calendar/moment.min.js'),
        'fullcalendar' => array('name' => 'assets/plugins/calendar/fullcalendar.min.js'),
        'fullcalendar-2' => array('name' => 'assets/plugins/calendar/fullcalendar.js'),
        'googlemaponline' => array('name' => "http://maps.googleapis.com/maps/api/js?key=AIzaSyCZAIzVxgsf-6BTZyDH35hfmgUFqBsgenI&libraries=weather,geometry,visualization,places,drawing&amp;", 'remote' => TRUE),
        'bootstrap-switch' => array('name' => 'assets/css/bootstrap/js/bootstrap-switch.js'),
        'jquery.datetimepicker' => array('name' => 'assets/plugins/datetimepicker-master/build/jquery.datetimepicker.full.min.js'),
        'bootbox.min' => array('name' => 'assets/js/bootbox.min.js'),
        'date' => array('name' => 'assets/js/date.js'),
        'jquery.date' => array('name' => 'assets/js/jquery.date.js'),
        'toastr' => array('name' => 'assets/plugins/toastr/toastr.js'),
        'qtip.min' => array('name' => 'assets/plugins/qtip/qtip.min.js'),
        'jquery-scrollbar' => array('name' => 'assets/plugins/jquery-scrollbar/jquery.mCustomScrollbar.js'),
        'client_live_feed' => array('name' => 'assets/js/client_live_feed.js'),
        'map' => array('name' => 'assets/public/js/map.js'),
        'jquery.easy-autocomplete' => array('name' => 'assets/plugins/EasyAutocomplete-1.3.5/jquery.easy-autocomplete.js'),
        'jquery.steps' => array('name' => 'assets/plugins/jquery-steps-master/jquery.steps.js'),
        'fileinput' => array('name' => 'assets/plugins/fileinput/fileinput.js'),
        'colorbox' => array('name' => 'assets/plugins/colorbox/jquery.colorbox.js'),
        'bootstrap-tagsinput' => array('name' => 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js'),
        'bootstrap-wysihtml5' => array('name' => 'assets/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js'),
        'jquery-ui' => array('name' => 'assets/public/js/jquery-ui.js'),
        'multiple-select' => array('name' => 'assets/plugins/multiple-select-master/multiple-select.js'),
        'jquery-tree' => array('name' => 'assets/plugins/jquery-tree-master/src/js/jquery.tree.js'),
        'select2' => array('name' => 'assets/plugins/select2/select2.js'),
        'jquery-ui-1.12.1.custom' => array('name' => 'assets/plugins/jquery-ui-1.12.1.custom/jquery-ui.js'),
        'bootstrap-tagsinput' => array('name' => 'assets/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js'),
        'bootstrap-select-1.11.2' => array('name' => 'assets/plugins/bootstrap-select-1.11.2/dist/js/bootstrap-select.js'),
        'jQuery-Autocomplete-master' => array('name' => 'assets/plugins/jQuery-Autocomplete-master/src/jquery.autocomplete.js'),
        'jquery.gmap' => array('name' => 'assets/js/jquery.gmap.js'),
        'jquery-ui.min' => array('name' => 'assets/js/jquery-ui.min.js'),
        'jquery.tipsy' => array('name' => 'assets/plugins/tipsy-master/src/javascripts/jquery.tipsy.js'),
        'main' => array('name' => 'assets/css/main.css'),
        'owl.carousel' => array('name' => 'assets/public/js/owl.carousel.min.js'),
        'jquery.fancybox' => array('name' => 'assets/public/js/fancybox/jquery.fancybox.js'),
        'google-map' => array('name' => "http://maps.googleapis.com/maps/api/js?key=AIzaSyCZAIzVxgsf-6BTZyDH35hfmgUFqBsgenI&libraries=weather,geometry,visualization,places,drawing&amp;", 'remote' => TRUE),
    );
    